# Generated by Django 4.2 on 2023-06-12 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=7)),
                ('account_holder', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='payments_from', to='ppss.bankaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='payments_to', to='ppss.bankaccount'),
        ),
    ]
