# Generated by Django 4.2 on 2023-06-12 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ppss', '0002_bankaccount_payment_bank_account_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('新規', '新規'), ('登録中', '登録中'), ('申請中', '申請中'), ('承認済み', '承認済み'), ('支払いデータ作成済み', '支払いデータ作成済み'), ('支払済み', '支払済み')], max_length=50),
        ),
        migrations.CreateModel(
            name='PaymentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppss.payment')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
