# Generated by Django 4.2 on 2023-06-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppss', '0005_customer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='branch_name',
            field=models.CharField(default='default_branch_name', max_length=20),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='branch_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=50),
        ),
    ]
