# Generated by Django 4.2 on 2023-06-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppss', '0006_bankaccount_branch_name_bankaccount_branch_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(default='default_branch_name', max_length=20)),
                ('branch_number', models.PositiveIntegerField(default=0)),
                ('account_number', models.PositiveIntegerField(default=0)),
                ('account_holder', models.CharField(max_length=30)),
            ],
        ),
    ]
